# -*- coding: utf-8 -*-
"""Hello_Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-zQS9BJIwQ8-kOgxramS-X_SwTiXoio
"""

import streamlit as st

st.title("Hello Streamlist World, this is TA")

st.header("Header")
st.subheader("Sub-header")

st.text("Please like this and subscribe to my Channel")

st.markdown(""" 
# h1 tag
## h2 tag
### h3 tag
:moon:<br>
:sunglasses:
** this is bold text **
"""True)